### ISSUE TITLE
Metadata in YAML header not shown on the knitted pdf document

### ISSUE THREAD

**Issue by kwanchmn** [jhollway/iheiddown#112]
**Describe the bug**
The metadata inputed in the YAML header does not show up in the knitted pdf document.

**To Reproduce**
1. Open an rmarkdown document with the "thesis" template in iheiddown
2. Input the metadata as indicated and write the text as needed
3. Knit the document and then the following warning message appears: `Warning message:
In system(paste0("iheiddown::thesis_pdf \"", input, "\"")) :
  'iheiddown::thesis_pdf' not found`
4. Comment out the `knit: iheiddown::thesis_pdf` and `output: iheiddown::thesis_pdf` options in the YAML header and then select the "knit to PDF" option for knitting the document
5. I can generate a knitted document but the metadata in the YAML header are not shown

**Expected behavior**
The knitted pdf document doesn't show these metadata as it would in other rmarkdown files. Instead, the document starts with the preface section directly.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Education 21H1]
 - R Version [4.1.1]
 - RStudio Version [2021.09.0 Build 351]

**Additional context**

**Comment by BBieri** [comment]
Hi !

Thanks for considering `{iheiddown}` to write your thesis and for reaching out!

While I was not able to replicate your error, I performed a clean install of the package from the GitHub repository and, as a result, knitting with all formats works for me. Let me walk you through what I did step by step:

- Remove the previous installation of `{iheidown}` by running: `utils::remove.packages("iheiddown")`
- Install `{iheidown}` from github by running: `remotes::install_github("jhollway/iheiddown")
  - Note that you need to install the `{remotes}` package for this with `install.packages("remotes")`
- Restart R upon successful installation of the package. This is for R to register the new templates when creating a new markdown file in RStudio. To do this simply click on `Session >> Restart R` in RStudio's menu bar at the top
- Create a thesis Rmd document and named the main file (the one with all the front matter options) `index.Rmd`
  - This is mandatory due to a strange `{bookdown}` error we were getting in previous versions of our package
- Knitted the document from the main file/`index.Rmd`

These steps produced a thesis with the front matter output that you seem to be missing as well as without the error you're mentionning in step 3. Could you please report back after following these steps as this might be useful for future users as well?

PS: The reason why you are not seeing the preface when commenting out the knit and output options is that we use a wrapper around bookdown's function to add these elements to the thesis template. In other words, these two lines are required for you to get the correct output.

**Comment by kwanchmn** [comment]
Hi!

Thanks for providing the steps needed for resolving the error that I raised earlier. I followed through the steps, and now everything is showing up properly at where they should be :) Seems like the main issue was that I didn't name the main file as `index.Rmd`. Once again a big thank you!

**Comment by BBieri** [comment]
Thanks for getting back so quickly! Glad that the steps I outlined above worked for you!

A PR is on its way this week and will hopefully make its way to CRAN soon too with all the latest features.
