### ISSUE TITLE
Add (markdown?) small caps support

### ISSUE THREAD

**Issue by jhollway** [jhollway/iheiddown#117]
- [ ] https://github.com/jgm/pandoc/issues/5256
- [ ] https://richardyan.site/markdown-test/#small-caps

**Comment by BBieri** [comment]
Is this a feature that we want to implement package-wide or only for a specific template?

**Comment by jhollway** [comment]
Ideally package-wide, though at least for thesis.

**Comment by BBieri** [comment]
After reading through the *long* discussion in the [pandoc issue](jgm/pandoc#5256) mentioned above, it appears that there is no way yet to integrate small caps natively from Markdown due to disagreements on how to implement it (e.g. use some type of asterisk combination).  Hence the issue will be solved as outlined below for now.

Regarding its integration into `{iheiddown}`, small caps have been implemented in HTML-based templates with a CSS selector called `.smallcaps`. As for the pdf templates, simply use `[Small caps]{.smallcaps}`.

Finally, note that results may vary depending on the font that is used as some do not have small caps support.
