### ISSUE TITLE
geneva syllabus csl renders whole bib entry red instead of just the year

### ISSUE THREAD

**Issue by jhollway** [jhollway/iheiddown#92]
Since upgrading RStudio to 1.4+ (with citation functionality built in), the geneva-syllabus.csl no longer renders only the year as red, but the whole entry.

**Comment by jhollway** [comment]
Not yet fixed: in this citation style, we still want the year to be in red and ideally contain the DOI or URL link.

**Comment by BBieri** [comment]
For posterity, this is most likely a Pandoc/citeproc issue since a version is bundled with RStudio and changes when updated to RStudio are done. On the problem itself, I have not found a way to alter the citation style to include hyperlinks in the date field. This is can't be done according to [this issue](https://github.com/citation-style-language/documentation/issues/76) via the CSL style and is left to the interpreters. Thus, one lead we could potentially follow is to create our own pandoc filter to add this "hyperlink on date" feature.

For now, due to time constraints, I have decided to use the `howpublished` attribute in the `bibtex` file as follows.
```
@Manual{iheiddown2020,
    title = {iheiddown: A RMarkdown class for IHEID dissertations},
    author = {Hollway, James},
    year = {2020},
    note = {R package version 0.0.1},
    howpublished = "\url{https://github.com/jhollway/iheiddown}",
    url = {https://github.com/jhollway/iheiddown},
  }
```

Which renders the following citation in the `.pdf` document with the URL at the end being clickable.
![image.png](https://images.zenhubusercontent.com/5fb64217ad906a65de7927e7/00a3714b-0181-4dde-9393-96a0546ee7b8)

**Comment by jhollway** [comment]
But `howpublished` is not an exported field from e.g. Zotero. Either close this issue and open a new one to collect ideas for a future release, or kick this back to someday/maybe.

**Comment by BBieri** [comment]
Kicked back to Someday/Maybe
